// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Slovion.Infrastructure.Persistence;

#nullable disable

namespace Slovion.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SlovionDbContext))]
    [Migration("20261002221318_AddQuests")]
    partial class AddQuests
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Slovion.Domain.Discovery.Encounter", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string[]>("Candidates")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("candidates");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("HabitatId")
                        .HasColumnType("text")
                        .HasColumnName("habitat_id");

                    b.Property<string>("MapId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("map_id");

                    b.Property<Guid>("SaveSlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("save_slot_id");

                    b.Property<string>("SpeciesId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("species_id");

                    b.Property<string>("SpotId")
                        .HasColumnType("text")
                        .HasColumnName("spot_id");

                    b.HasKey("Id");

                    b.HasIndex("SaveSlotId")
                        .IsUnique()
                        .HasDatabaseName("ix_encounters_one_open_per_save_slot")
                        .HasFilter("closed_at IS NULL");

                    b.ToTable("encounters", (string)null);
                });

            modelBuilder.Entity("Slovion.Domain.Discovery.SpeciesDiscovery", b =>
                {
                    b.Property<Guid>("SaveSlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("save_slot_id");

                    b.Property<string>("SpeciesId")
                        .HasColumnType("text")
                        .HasColumnName("species_id");

                    b.Property<string>("HabitatId")
                        .HasColumnType("text")
                        .HasColumnName("habitat_id");

                    b.Property<DateTimeOffset?>("IdentifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("identified_at");

                    b.Property<string>("MapId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("map_id");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<string>("SpotId")
                        .HasColumnType("text")
                        .HasColumnName("spot_id");

                    b.HasKey("SaveSlotId", "SpeciesId");

                    b.ToTable("discoveries", (string)null);
                });

            modelBuilder.Entity("Slovion.Domain.Quests.QuestProgress", b =>
                {
                    b.Property<Guid>("SaveSlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("save_slot_id");

                    b.Property<string>("QuestId")
                        .HasColumnType("text")
                        .HasColumnName("quest_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.HasKey("SaveSlotId", "QuestId");

                    b.ToTable("quest_progress", (string)null);
                });

            modelBuilder.Entity("Slovion.Domain.Saves.SaveSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("save_slots", (string)null);
                });

            modelBuilder.Entity("Slovion.Domain.Discovery.Encounter", b =>
                {
                    b.HasOne("Slovion.Domain.Saves.SaveSlot", null)
                        .WithMany()
                        .HasForeignKey("SaveSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Slovion.Domain.Discovery.SpeciesDiscovery", b =>
                {
                    b.HasOne("Slovion.Domain.Saves.SaveSlot", null)
                        .WithMany()
                        .HasForeignKey("SaveSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Slovion.Domain.Quests.QuestProgress", b =>
                {
                    b.HasOne("Slovion.Domain.Saves.SaveSlot", null)
                        .WithMany()
                        .HasForeignKey("SaveSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
