// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Slovion.Infrastructure.Persistence;

#nullable disable

namespace Slovion.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SlovionDbContext))]
    partial class SlovionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Slovion.Domain.Discovery.SpeciesDiscovery", b =>
                {
                    b.Property<Guid>("SaveSlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("save_slot_id");

                    b.Property<string>("SpeciesId")
                        .HasColumnType("text")
                        .HasColumnName("species_id");

                    b.Property<DateTimeOffset>("DiscoveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("discovered_at");

                    b.Property<string>("MapId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("map_id");

                    b.Property<string>("SpotId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("spot_id");

                    b.HasKey("SaveSlotId", "SpeciesId");

                    b.ToTable("discoveries", (string)null);
                });

            modelBuilder.Entity("Slovion.Domain.Saves.SaveSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("save_slots", (string)null);
                });

            modelBuilder.Entity("Slovion.Domain.Discovery.SpeciesDiscovery", b =>
                {
                    b.HasOne("Slovion.Domain.Saves.SaveSlot", null)
                        .WithMany()
                        .HasForeignKey("SaveSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
